### ISSUE TITLE
Authentication/authorization ?

### ISSUE THREAD

**Issue by aksonov** [graphql-perl/GraphQL-Plugin-Convert-DBIC#8]
Could you help me how to restrict mutations/queries depending from logged/unlogged user?

**Comment by mohawk2** [comment]
At the moment there isn't a fantastically easy way, but there is nevertheless a way. You will need to supply your own [resolver function](https://metacpan.org/pod/GraphQL::Type::Library#FieldMapOutput). Your function will make an allow/disallow decision based on the passed-in `$info` contents, seeing whether you want to restrict that field, or class of fields (eg by `parent_type` being `Mutation`); and the `$context`, which is per-request.

The `$context` passed in by [Mojolicious::Plugin::GraphQL](https://metacpan.org/pod/Mojolicious::Plugin::GraphQL) is by default the request-headers, but the doc for that module shows you how you can change that.

Very broadly, you'll probably want a "login" query whose return type is a "Permission" type that your client can then read e.g. a token from, and send back as an HTTP header (probably "Authorization") that your resolver checks. If the check fails, then doing a `die` with suitable error message, probably giving which query to login with, will return an informative GraphQL error.

I would be very interested if you share on here what you find, since that may make it easy to generalise. Good luck!

**Comment by aksonov** [comment]
Thanks for fast answer! Custom resolvers look very interesting, do you know any graphql examples? Example from docs looks quite unclear (i.e. how to make it work with Plugin::Convert::DBIC). Where to pass created graphql schema (`$converted`) ? 

```
sub _make_moo_field {
  my ($field_name, $type) = @_;
  ($field_name => { resolve => sub {
    my ($root_value, $args, $context, $info) = @_;
    my @passon = %$args ? ($args) : ();
    return undef unless $root_value->can($field_name);
    $root_value->$field_name(@passon);
  }, type => $type });
}
# ...
  fields => {
    _make_moo_field(name => $String),
    _make_moo_field(description => $String),
  },
# ...

```

**Comment by mohawk2** [comment]
You might get `$converted` from the `to_graphql`, which is [documented](https://metacpan.org/pod/GraphQL::Plugin::Convert) to return a hash. You could then replace the `resolver` value in that hash with your own, but based on the [DBIC resolver](https://metacpan.org/source/ETJ/GraphQL-Plugin-Convert-DBIC-0.08/lib/GraphQL/Plugin/Convert/DBIC.pm#L201) - for now you'd start by copy-pasting, but as mentioned above, if you share what you come up with, that will probably tell me how to make "hooks" available for easier use!

**Comment by aksonov** [comment]
@mohawk2 Looks clear now, I will try, thanks!

**Comment by mohawk2** [comment]
Tell me how it goes :-)

**Comment by aksonov** [comment]
I've generated schema from https://github.com/datacharmer/test_db using `dbicdump` and tried to run following:
```
use GraphQL::Plugin::Convert::DBIC;
use lib 'lib';
use Schema;
my $converted = GraphQL::Plugin::Convert::DBIC->to_graphql(
  sub { Schema->connect('dbi:mysql:employees') }
);
print $converted->{schema}->to_doc;
```

I've got following error:
```
Use of uninitialized value $source in substitution (s///) at /Users/aksonov/perl5/lib/perl5/GraphQL/Plugin/Convert/DBIC.pm line 118.
Use of uninitialized value $source in split at /Users/aksonov/perl5/lib/perl5/GraphQL/Plugin/Convert/DBIC.pm line 120.
Value "" did not pass type constraint "StrNameValid" (in $args->{"name"}) at /Users/aksonov/perl5/lib/perl5/GraphQL/Type/Enum.pm line 145
    "StrNameValid" is a subtype of "StrMatch[(?^u:^[_a-zA-Z][_a-zA-Z0-9]*$)]"
    Value "" did not pass type constraint "StrMatch[(?^u:^[_a-zA-Z][_a-zA-Z0-9]*$)]" (in $args->{"name"})
    "StrMatch[(?^u:^[_a-zA-Z][_a-zA-Z0-9]*$)]" is defined as: do { !ref($_) and $_ =~ $Types::Standard::StrMatch::expressions{"Regexp|(?^u:^[_a-zA-Z][_a-zA-Z0-9]*\$)"} }
```

**Comment by mohawk2** [comment]
For future reference:

```
git clone git@github.com:datacharmer/test_db.git
cd test_db
grep -v '^source' employees.sql | mysql # no data-load, just DDL
dbicdump -o dump_directory=./lib MyApp::Schema dbi:mysql:employees
perl -MGraphQL::Plugin::Convert::DBIC -Ilib -MMyApp::Schema \
 -e 'print GraphQL::Plugin::Convert::DBIC->to_graphql(sub { MyApp::Schema->connect("dbi:mysql:employees") })->{schema}->to_doc'
```

I have successfully repro-ed the problem using the above.

**Comment by mohawk2** [comment]
I have now added the DBIC dump as a test-case, and fixed both the enum problem, then a problem with relations and views. Now released as 0.10. Any problems, let me know!

**Comment by aksonov** [comment]
```
Result: PASS
  ETJ/GraphQL-Plugin-Convert-DBIC-0.09.tar.gz
  /usr/bin/make test -- OK
Running make install
Manifying 2 pod documents
Installing /Users/aksonov/perl5/lib/perl5/GraphQL/Plugin/Convert/DBIC.pm
Installing /Users/aksonov/perl5/man/man3/GraphQL::Plugin::Convert::DBIC.3pm
Appending installation info to /Users/aksonov/perl5/lib/perl5/darwin-thread-multi-2level/perllocal.pod
  ETJ/GraphQL-Plugin-Convert-DBIC-0.09.tar.gz
  /usr/bin/make install  -- OK
```

Looks like CPAN still uses 0.09 version

**Comment by mohawk2** [comment]
I released 0.09 a bit before. Try now, it takes a little while to catch up. If it's still wrong, try `cpanm GraphQL::Plugin::Convert::DBIC@0.10`.

**Comment by aksonov** [comment]
0.10.0 works fine, thanks! However, could you update Example section? I've tried both ways from docs and they both output `Not a CODE reference at /Users/aksonov/perl5/lib/perl5/GraphQL/Plugin/Convert/DBIC.pm line 237.`

```
package GraphQL::Plugin::Convert::DBIC;
use Moo;
extends qw(GraphQL::Plugin::Convert);
# ...
 
package main;
use Mojolicious::Lite;
use Schema;
use GraphQL::Plugin::Convert::DBIC;
helper db => sub { Schema->connect('dbi:SQLite:test.db') };
my $converted = GraphQL::Plugin::Convert::DBIC->to_graphql(app->db);
plugin GraphQL => {
  map { $_ => $converted->{$_} }
    qw(schema resolver root_value)
};
 
# OR, for knowledgeable consumers of GraphQL::Plugin::Convert APIs:
package main;
use Mojolicious::Lite;
use Schema;
helper db => sub { Schema->connect('dbi:SQLite:test.db') };
plugin GraphQL => { convert => [ 'DBIC', app->db ] };
```

It works well when I added `{ convert => ['DBIC', sub { app->db} ] };` but I'm not sure what to do if I want to change `$converted` (i.e. use first case)

**Comment by aksonov** [comment]
And how to add graphiql option to first case too? Mojo & graphql `convert` syntax is very new for me, where I can read more about that?

**Comment by aksonov** [comment]
Never mind, I solved it by replacing `app->db` with `sub { app->db } ` within `to_graphql`

**Comment by mohawk2** [comment]
I will fix the relevant doc, thanks for pointing this out. It would have saved me a few minutes if you'd included which doc you were talking about. I'm closing this issue, since the authorisation matter is apparently resolved. If you find other things, please open new issues as necessary, being careful to put them on the right repo :-)
